version: '3'
services:
  dev:
    build: .
    image: histrio/devdocker:latest
    ports:
      - "8023:22"
      - "60000-60100:60000-60100/udp"
    volumes:
        - workspace:/home/histrio/workspace
    hostname: dev

volumes:
  workspace:
